---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: facebooc
  namespace: facebooc
spec:
  healthChecks:
  - kind: Deployment
    name: facebooc
    namespace: facebooc
  interval: 1m0s
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: facebooc
  targetNamespace: facebooc
  timeout: 3m0s
  validation: client

